### ISSUE TITLE
Discussion of socket implementation

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#10]
- Is it possible to treat a socket as a file directly? 
  `sockfs`: `impl INode for Socket`
- If we can, what should be added to the current VFS?
- If not, can we design a socket trait to isolate syscall and network stack?

@jiegec Orz

**Comment by jiegec** [comment]
* Is it possible to treat a socket as a file directly?
    - It let me think of Plan9 OS.
    - Hard, the syscalls needed to support have different semantics, but easy if we just throw then away.
* If we can, what should be added to the current VFS?
    - /dev/tcp/addr/port? (as in bash)
    - Use ioctl for specific operations other than writing and reading?
* If not, can we design a socket trait to isolate syscall and network stack?
    - Yes. I think we can delegate syscall to each type of socket struct.

**Comment by wangrunji0408** [comment]
👍Nice!
