### ISSUE TITLE
Prepare user programs for RISCV

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#21]
### Port Biscuit programs to RISCV
Ref: [riscv-musl](https://github.com/riscv/riscv-musl), build pass.

### Build Busybox for RISCV
I tried but failed.
Ref: [qemu运行riscv linux](http://www.zihaochang.com/2018/02/02/qemu-run-riscv/#四、编译busybox)

**Comment by wangrunji0408** [comment]
@jiegec found a prebuilt binary of Busybox on Debian: [busybox-static](https://packages.debian.org/sid/busybox-static).
Then we noticed that the syscall ids are different across platforms.

**Comment by jiegec** [comment]
Problem: glibc TLS is not working at the minute.

**Comment by jiegec** [comment]
Syscall id inconsistency is fixed by @jiegec and @equation314

**Comment by jiegec** [comment]
Busybox for RISC-V is available at https://github.com/rcore-os/busybox-riscv-prebuilts

**Comment by jiegec** [comment]
It works now.
