### ISSUE TITLE
Test rCore on x86_64 real machine

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#23]
- ~~Enable VGA 320x200~~
- [x] Fix VGA text color and kill escape code
- [x] Fix keyboard input (it's actually VGA bug)
- [x] Fix multicore boot
- [x] Fix serial dead lock
- [x] Fix other bugs

**Comment by jiegec** [comment]
Works in my i7-6700 machine as well.
Two ixgbe functions are up and running.
