### ISSUE TITLE
Recycle tid on sys_wait4

### ISSUE THREAD

**Issue by jiegec** [oscourse-tsinghua/rcore_plus#25]

**Comment by jiegec** [comment]
Possible solutions:
1. Quit whole process when main thread exits.
2. Never recycle tid until whole process exits.
3. Only recycle non-main thread before process exits, and recycle main thread id upon sys_wait.

**Comment by wangrunji0408** [comment]
4. Detach pid and tid. Recycle tid once the thread exits. (?)

**Comment by wangrunji0408** [comment]
Current solution (No.4):
* ab62d54: Detach pid and tid. Now the pid is no longer the tid of its first thread.
* 27f5c7b: Detach user thread by default, so that it will release its tid on exit.
