### ISSUE TITLE
Simplify virtual memory management

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#37]
The current code structure is confusing!
The recursive mapping is really hard to understand and make the code more complicated.

BlogOS has replaced recursive mapping by linear mapping all physical memory.
See discussions here: https://github.com/phil-opp/blog_os/issues/545.

Some ideas:
* Deprecate `InactivePageTable` and only access `ActivePageTable`

  * Remove `remap_the_kernel` from kernel.
  * Build a fine page table for kernel in bootloader (as x86_64 did).
  * Let `MemorySet` owns `&'static mut ActivePageTable`

* Move arch-specific page table implementation to memory crate

**Comment by Harry-Chen** [comment]
@miskcoo is doing similar work on mipsel platform. Maybe he will be interested.
