### ISSUE TITLE
Fix busybox sh and use it as default shell

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#40]
Now busybox sh has these bugs:
- [x] Failed to echo input
- [x] Can't fork on RISCV

**Comment by jiegec** [comment]
We don't have a tty now, so we may need to hack something.

**Comment by jiegec** [comment]
It works now.

**Comment by jiegec** [comment]
We need to have a PATH env now.

**Comment by wangrunji0408** [comment]
Super fast progress!
