### ISSUE TITLE
Merge new features from OS2019 projects

### ISSUE THREAD

**Issue by wangrunji0408** [oscourse-tsinghua/rcore_plus#55]
## OS2019 projects
* wiki: [2019年操作系统课程设计：教学操作系统rcore+的改进和扩展](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects)
* upstream branch: [rCore/dev](https://github.com/rcore-os/rCore/tree/dev) & [rcore_plus/dev](https://github.com/oscourse-tsinghua/rcore_plus/tree/dev)

### GBA
* authors: @PanQL @xy-plus
* wiki: [简易版 rcore 开发与教学文档编写 && rcore plus 开发](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g02)
* branch: [rcore_plus/mgba](https://github.com/oscourse-tsinghua/rcore_plus/tree/mgba)
* platform: x86_64
* last merge to dev: 8e5e798d 2019.06.03
* PRs: (null)
* status: ✅

### MIPS
* authors: @Harry-Chen  @miskcoo 
* wiki: [第三届全国大学生系统能力培养大赛](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g03)
* branch: [rcore_plus/mipsel](https://github.com/oscourse-tsinghua/rcore_plus/tree/mipsel)
* platform: mipsel
* last merge to dev: f410aef 2019.05.24
* PRs: [rCore#8](https://github.com/rcore-os/rCore/pull/8)
* status: ✅

### Router
* authors: @jiegec @Jackey-Huo
* wiki: [FPGA 上运行 RISC-V rCore 构建路由器](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g05)
* branch: [rCore/dev](https://github.com/rcore-os/rCore/tree/dev)
* platform: riscv64
* last merge to dev: realtime
* PRs: (null)
* status: ✅

### LKM
* authors: @gjz010
* wiki: [rCore 内核可加载模块和动态链接库](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g06)
* branch: [gjz010/rcore_plus/biscuit](https://github.com/gjz010/rcore_plus/tree/biscuit)
* platform: x86_64, aarch64
* last merge to dev: 6aded707 2019.06.13
* PRs: #48 #57 #58 #59 #60 
* status: 🚧

### Audio on Raspi3
* authors: @gaotianyu1350 @Bakser
* wiki: [Audio support for rCore](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g08)
* branch: [gaotianyu1350/rCore_audio/dev](https://github.com/gaotianyu1350/rCore_audio/tree/dev)
* platform: aarch64
* last merge to dev: (null)
* PRs: [rcore-fs#5](https://github.com/rcore-os/rcore-fs/pull/5) [bcm2837#1](https://github.com/rcore-os/bcm2837/pull/1)
* status: ❓

### SD driver on Raspi3
* authors: @NagiNikaido @BenjaminPMLovegood
* wiki: [Python (and more) on rCore on RPi](http://os.cs.tsinghua.edu.cn/oscourse/OS2019spring/projects/g11)
* branch: [GeminiLab/rCore/geminilab
](https://github.com/GeminiLab/rCore/tree/geminilab)
* platform: aarch64
* last merge to dev: fa7e3895 2019.06.03
* PRs: (null)
* status: ❓

**Comment by jiegec** [comment]
SD driver on Raspi3 seems good to go. Maybe @NagiNikaido @BenjaminPMLovegood can do some code cleanup? e.g. change these test outputs:

```
Re-fetched content:
DE AD BE EF DE AD BE EF DE AD BE EF DE AD BE EF
```

Already merged their bcm2837 into upstream.

Update: I made the merge manually.

**Comment by jiegec** [comment]
bcm2837 changes from https://github.com/rcore-os/bcm2837/pull/1 still need some work. Kernel part is easier to merge IMO: https://github.com/rcore-os/rCore/compare/dev...gaotianyu1350:dev?expand=1

**Comment by Harry-Chen** [comment]
MIPS part is fully merged to `dev` branch.
