### ISSUE TITLE
how to build a customized std?

### ISSUE THREAD

**Issue by chyyuu** [oscourse-tsinghua/rcore_plus#7]
I only found https://github.com/Thinkofname/xargo

But I don't know how to modify std (no syscall, just function call) and add a mini std based app directly into kernel? 

@wangrunji0408

**Comment by chyyuu** [comment]
[How do I build the Rust standard library with a custom musl?](https://stackoverflow.com/questions/42192850/how-do-i-build-the-rust-standard-library-with-a-custom-musl)  looks like a reference.
But I don't know how to do it.

**Comment by wangrunji0408** [comment]
### Build with customized std
Both `xargo` and `cargo-xbuild` support building with a customized std. 

As their README saying:
```sh
# The source of the `core` crate must be in `$XARGO_RUST_SRC/libcore`
export XARGO_RUST_SRC=/path/to/rust/src
cargo xbuild  # or: xargo build
```

But I tried and met some problems.

### Modify std
It seems that we can just create a new implementation at [libstd/sys](https://github.com/rust-lang/rust/tree/master/src/libstd/sys).
And I will try it later.

**Comment by wangrunji0408** [comment]
I figured it out. See the wiki page: 
[How to build std Rust programs with customized musl libc.](https://github.com/oscourse-tsinghua/rcore_plus/wiki/How-to-build-std-Rust-programs-with-customized-musl-libc.)
